// Static problem data for TLE Eliminators, USACO Guide, and CSES
export const TLE_PROBLEMS = [
    // Rating 800
    { name: "Watermelon", link: "https://codeforces.com/problemset/problem/4/A", rating: "800", order: 1 },
    { name: "Way Too Long Words", link: "https://codeforces.com/problemset/problem/71/A", rating: "800", order: 2 },
    { name: "Team", link: "https://codeforces.com/problemset/problem/231/A", rating: "800", order: 3 },
    { name: "Bit++", link: "https://codeforces.com/problemset/problem/282/A", rating: "800", order: 4 },
    { name: "Domino piling", link: "https://codeforces.com/problemset/problem/50/A", rating: "800", order: 5 },
    { name: "Beautiful Matrix", link: "https://codeforces.com/problemset/problem/263/A", rating: "800", order: 6 },
    { name: "Petya and Strings", link: "https://codeforces.com/problemset/problem/112/A", rating: "800", order: 7 },
    { name: "Football", link: "https://codeforces.com/problemset/problem/96/A", rating: "800", order: 8 },
    { name: "String Task", link: "https://codeforces.com/problemset/problem/118/A", rating: "800", order: 9 },
    { name: "Helpful Maths", link: "https://codeforces.com/problemset/problem/339/A", rating: "800", order: 10 },
    { name: "Word Capitalization", link: "https://codeforces.com/problemset/problem/281/A", rating: "800", order: 11 },
    { name: "Boy or Girl", link: "https://codeforces.com/problemset/problem/236/A", rating: "800", order: 12 },
    { name: "Stones on the Table", link: "https://codeforces.com/problemset/problem/266/A", rating: "800", order: 13 },
    { name: "Bear and Big Brother", link: "https://codeforces.com/problemset/problem/791/A", rating: "800", order: 14 },
    { name: "Soldier and Bananas", link: "https://codeforces.com/problemset/problem/546/A", rating: "800", order: 15 },
    { name: "Elephant", link: "https://codeforces.com/problemset/problem/617/A", rating: "800", order: 16 },
    { name: "Wrongsubtraction", link: "https://codeforces.com/problemset/problem/977/A", rating: "800", order: 17 },
    { name: "Word", link: "https://codeforces.com/problemset/problem/59/A", rating: "800", order: 18 },
    { name: "Magnets", link: "https://codeforces.com/problemset/problem/344/A", rating: "800", order: 19 },
    { name: "Sereja and Dima", link: "https://codeforces.com/problemset/problem/381/A", rating: "800", order: 20 },
    { name: "Tram", link: "https://codeforces.com/problemset/problem/116/A", rating: "800", order: 21 },
    { name: "Nearly Lucky Number", link: "https://codeforces.com/problemset/problem/110/A", rating: "800", order: 22 },
    { name: "Anton and Danik", link: "https://codeforces.com/problemset/problem/734/A", rating: "800", order: 23 },
    { name: "George and Accommodation", link: "https://codeforces.com/problemset/problem/467/A", rating: "800", order: 24 },
    { name: "Queue at the School", link: "https://codeforces.com/problemset/problem/266/B", rating: "800", order: 25 },
    { name: "Borze", link: "https://codeforces.com/problemset/problem/32/B", rating: "800", order: 26 },
    { name: "Beautiful Year", link: "https://codeforces.com/problemset/problem/271/A", rating: "800", order: 27 },
    { name: "Drinks", link: "https://codeforces.com/problemset/problem/200/B", rating: "800", order: 28 },
    { name: "Insomnia cure", link: "https://codeforces.com/problemset/problem/148/A", rating: "800", order: 29 },
    { name: "Game With Sticks", link: "https://codeforces.com/problemset/problem/451/A", rating: "800", order: 30 },

    // Rating 900
    { name: "Twins", link: "https://codeforces.com/problemset/problem/160/A", rating: "900", order: 1 },
    { name: "Presents", link: "https://codeforces.com/problemset/problem/136/A", rating: "900", order: 2 },
    { name: "Is your horseshoe on the other hoof?", link: "https://codeforces.com/problemset/problem/228/A", rating: "900", order: 3 },
    { name: "I Wanna Be the Guy", link: "https://codeforces.com/problemset/problem/469/A", rating: "900", order: 4 },
    { name: "Arrival of the General", link: "https://codeforces.com/problemset/problem/144/A", rating: "900", order: 5 },
    { name: "Lights Out", link: "https://codeforces.com/problemset/problem/275/A", rating: "900", order: 6 },
    { name: "Lucky Division", link: "https://codeforces.com/problemset/problem/122/A", rating: "900", order: 7 },
    { name: "Even Odds", link: "https://codeforces.com/problemset/problem/318/A", rating: "900", order: 8 },
    { name: "Amusing Joke", link: "https://codeforces.com/problemset/problem/141/A", rating: "900", order: 9 },
    { name: "HQ9+", link: "https://codeforces.com/problemset/problem/133/A", rating: "900", order: 10 },
    { name: "Ultra-Fast Mathematician", link: "https://codeforces.com/problemset/problem/61/A", rating: "900", order: 11 },
    { name: "Dubstep", link: "https://codeforces.com/problemset/problem/208/A", rating: "900", order: 12 },
    { name: "Panoramix's Prediction", link: "https://codeforces.com/problemset/problem/80/A", rating: "900", order: 13 },
    { name: "Young Physicist", link: "https://codeforces.com/problemset/problem/69/A", rating: "900", order: 14 },
    { name: "Beautiful Strings", link: "https://codeforces.com/problemset/problem/262/A", rating: "900", order: 15 },
    { name: "Gravity Flip", link: "https://codeforces.com/problemset/problem/405/A", rating: "900", order: 16 },
    { name: "Translation", link: "https://codeforces.com/problemset/problem/41/A", rating: "900", order: 17 },
    { name: "Football", link: "https://codeforces.com/problemset/problem/43/A", rating: "900", order: 18 },
    { name: "Vanya and Fence", link: "https://codeforces.com/problemset/problem/677/A", rating: "900", order: 19 },
    { name: "Word", link: "https://codeforces.com/problemset/problem/59/A", rating: "900", order: 20 },
    { name: "Candies and Two Sisters", link: "https://codeforces.com/problemset/problem/1335/A", rating: "900", order: 21 },
    { name: "Police Recruits", link: "https://codeforces.com/problemset/problem/427/A", rating: "900", order: 22 },
    { name: "Black Square", link: "https://codeforces.com/problemset/problem/431/A", rating: "900", order: 23 },
    { name: "Night at the Museum", link: "https://codeforces.com/problemset/problem/731/A", rating: "900", order: 24 },
    { name: "Buy a Shovel", link: "https://codeforces.com/problemset/problem/732/A", rating: "900", order: 25 },
    { name: "Calculating Function", link: "https://codeforces.com/problemset/problem/486/A", rating: "900", order: 26 },
    { name: "New Password", link: "https://codeforces.com/problemset/problem/770/A", rating: "900", order: 27 },
    { name: "Colorful Stones", link: "https://codeforces.com/problemset/problem/265/A", rating: "900", order: 28 },
    { name: "Shaass and Oskols", link: "https://codeforces.com/problemset/problem/294/A", rating: "900", order: 29 },
    { name: "Valera and X", link: "https://codeforces.com/problemset/problem/404/A", rating: "900", order: 30 },

    // Rating 1000
    { name: "Raising Bacteria", link: "https://codeforces.com/problemset/problem/579/A", rating: "1000", order: 1 },
    { name: "Chewbaсca and Number", link: "https://codeforces.com/problemset/problem/514/A", rating: "1000", order: 2 },
    { name: "Puzzles", link: "https://codeforces.com/problemset/problem/337/A", rating: "1000", order: 3 },
    { name: "Keyboard", link: "https://codeforces.com/problemset/problem/474/A", rating: "1000", order: 4 },
    { name: "Chat room", link: "https://codeforces.com/problemset/problem/58/A", rating: "1000", order: 5 },
    { name: "Divisibility Problem", link: "https://codeforces.com/problemset/problem/1328/A", rating: "1000", order: 6 },
    { name: "Honest Coach", link: "https://codeforces.com/problemset/problem/1360/B", rating: "1000", order: 7 },
    { name: "Soft Drinking", link: "https://codeforces.com/problemset/problem/151/A", rating: "1000", order: 8 },
    { name: "Dice Tower", link: "https://codeforces.com/problemset/problem/225/A", rating: "1000", order: 9 },
    { name: "Kefa and First Steps", link: "https://codeforces.com/problemset/problem/580/A", rating: "1000", order: 10 },
    { name: "Dragons", link: "https://codeforces.com/problemset/problem/230/A", rating: "1000", order: 11 },
    { name: "Odd Divisor", link: "https://codeforces.com/problemset/problem/1475/A", rating: "1000", order: 12 },
    { name: "Bachgold Problem", link: "https://codeforces.com/problemset/problem/749/A", rating: "1000", order: 13 },
    { name: "Remove Smallest", link: "https://codeforces.com/problemset/problem/1399/A", rating: "1000", order: 14 },
    { name: "Ternary String", link: "https://codeforces.com/problemset/problem/1354/B", rating: "1000", order: 15 },
    { name: "Fence", link: "https://codeforces.com/problemset/problem/363/B", rating: "1000", order: 16 },
    { name: "Balanced Array", link: "https://codeforces.com/problemset/problem/1343/B", rating: "1000", order: 17 },
    { name: "Candies", link: "https://codeforces.com/problemset/problem/1343/A", rating: "1000", order: 18 },
    { name: "Registration system", link: "https://codeforces.com/problemset/problem/4/C", rating: "1000", order: 19 },
    { name: "Pashmak and Flowers", link: "https://codeforces.com/problemset/problem/459/B", rating: "1000", order: 20 },
    { name: "Lineland Mail", link: "https://codeforces.com/problemset/problem/567/A", rating: "1000", order: 21 },
    { name: "Effective Approach", link: "https://codeforces.com/problemset/problem/227/B", rating: "1000", order: 22 },
    { name: "Polo the Penguin and Segments", link: "https://codeforces.com/problemset/problem/289/A", rating: "1000", order: 23 },
    { name: "Codeforces Checking", link: "https://codeforces.com/problemset/problem/1791/A", rating: "1000", order: 24 },
    { name: "Sum of Round Numbers", link: "https://codeforces.com/problemset/problem/1352/A", rating: "1000", order: 25 },
    { name: "Minimal Cost", link: "https://codeforces.com/problemset/problem/1491/A", rating: "1000", order: 26 },
    { name: "Shuffle Hashing", link: "https://codeforces.com/problemset/problem/1278/A", rating: "1000", order: 27 },
    { name: "Orac and Factors", link: "https://codeforces.com/problemset/problem/1350/A", rating: "1000", order: 28 },
    { name: "Minimal Square", link: "https://codeforces.com/problemset/problem/1360/A", rating: "1000", order: 29 },
    { name: "Restoring Three Numbers", link: "https://codeforces.com/problemset/problem/1154/A", rating: "1000", order: 30 },

    // Rating 1100
    { name: "Vanya and Lanterns", link: "https://codeforces.com/problemset/problem/492/B", rating: "1100", order: 1 },
    { name: "Books", link: "https://codeforces.com/problemset/problem/279/B", rating: "1100", order: 2 },
    { name: "Burning Midnight Oil", link: "https://codeforces.com/problemset/problem/165/B", rating: "1100", order: 3 },
    { name: "Worms", link: "https://codeforces.com/problemset/problem/474/B", rating: "1100", order: 4 },
    { name: "Interesting drink", link: "https://codeforces.com/problemset/problem/706/B", rating: "1100", order: 5 },
    { name: "Kuriyama Mirai's Stones", link: "https://codeforces.com/problemset/problem/433/B", rating: "1100", order: 6 },
    { name: "Sereja and Suffixes", link: "https://codeforces.com/problemset/problem/368/B", rating: "1100", order: 7 },
    { name: "Ilya and Queries", link: "https://codeforces.com/problemset/problem/313/B", rating: "1100", order: 8 },
    { name: "Little Girl and Maximum Sum", link: "https://codeforces.com/problemset/problem/276/C", rating: "1100", order: 9 },
    { name: "Greg's Workout", link: "https://codeforces.com/problemset/problem/255/A", rating: "1100", order: 10 },
    { name: "Xenia and Ringroad", link: "https://codeforces.com/problemset/problem/339/B", rating: "1100", order: 11 },
    { name: "Yaroslav and Permutations", link: "https://codeforces.com/problemset/problem/296/A", rating: "1100", order: 12 },
    { name: "Dima and Friends", link: "https://codeforces.com/problemset/problem/272/A", rating: "1100", order: 13 },
    { name: "Vasya the Hipster", link: "https://codeforces.com/problemset/problem/581/A", rating: "1100", order: 14 },
    { name: "Counterexample", link: "https://codeforces.com/problemset/problem/483/A", rating: "1100", order: 15 },
    { name: "Sail", link: "https://codeforces.com/problemset/problem/298/B", rating: "1100", order: 16 },
    { name: "Dreamoon and Stairs", link: "https://codeforces.com/problemset/problem/476/A", rating: "1100", order: 17 },
    { name: "Jzzhu and Children", link: "https://codeforces.com/problemset/problem/450/A", rating: "1100", order: 18 },
    { name: "Reconnaissance 2", link: "https://codeforces.com/problemset/problem/34/A", rating: "1100", order: 19 },
    { name: "Decoding", link: "https://codeforces.com/problemset/problem/746/B", rating: "1100", order: 20 },
    { name: "Taxi", link: "https://codeforces.com/problemset/problem/158/B", rating: "1100", order: 21 },
    { name: "Sale", link: "https://codeforces.com/problemset/problem/34/B", rating: "1100", order: 22 },
    { name: "Lecture", link: "https://codeforces.com/problemset/problem/499/B", rating: "1100", order: 23 },
    { name: "Combination Lock", link: "https://codeforces.com/problemset/problem/540/A", rating: "1100", order: 24 },
    { name: "Ksenia and Pan Scales", link: "https://codeforces.com/problemset/problem/382/A", rating: "1100", order: 25 },
    { name: "Fancy Fence", link: "https://codeforces.com/problemset/problem/270/A", rating: "1100", order: 26 },
    { name: "Parallelepiped", link: "https://codeforces.com/problemset/problem/224/A", rating: "1100", order: 27 },
    { name: "Cifera", link: "https://codeforces.com/problemset/problem/114/A", rating: "1100", order: 28 },
    { name: "Comparing Strings", link: "https://codeforces.com/problemset/problem/186/A", rating: "1100", order: 29 },
    { name: "Chips", link: "https://codeforces.com/problemset/problem/333/A", rating: "1100", order: 30 },

    // Rating 1200
    { name: "T-primes", link: "https://codeforces.com/problemset/problem/230/B", rating: "1200", order: 1 },
    { name: "Appleman and Easy Task", link: "https://codeforces.com/problemset/problem/462/A", rating: "1200", order: 2 },
    { name: "Xenia and Bit Operations", link: "https://codeforces.com/problemset/problem/339/D", rating: "1200", order: 3 },
    { name: "Yaroslav and Permutations", link: "https://codeforces.com/problemset/problem/296/A", rating: "1200", order: 4 },
    { name: "Dima and Continuous Line", link: "https://codeforces.com/problemset/problem/296/C", rating: "1200", order: 5 },
    { name: "Vitaly and Strings", link: "https://codeforces.com/problemset/problem/518/A", rating: "1200", order: 6 },
    { name: "Towers", link: "https://codeforces.com/problemset/problem/37/A", rating: "1200", order: 7 },
    { name: "Dima and Staircase", link: "https://codeforces.com/problemset/problem/272/C", rating: "1200", order: 8 },
    { name: "Vasya and Socks", link: "https://codeforces.com/problemset/problem/460/A", rating: "1200", order: 9 },
    { name: "Inna and Choose Options", link: "https://codeforces.com/problemset/problem/400/A", rating: "1200", order: 10 },
    { name: "Suffix Structures", link: "https://codeforces.com/problemset/problem/448/A", rating: "1200", order: 11 },
    { name: "Alyona and Numbers", link: "https://codeforces.com/problemset/problem/682/A", rating: "1200", order: 12 },
    { name: "Petr and Book", link: "https://codeforces.com/problemset/problem/139/A", rating: "1200", order: 13 },
    { name: "Polo the Penguin and Matrix", link: "https://codeforces.com/problemset/problem/289/B", rating: "1200", order: 14 },
    { name: "Inna and Pink Pony", link: "https://codeforces.com/problemset/problem/374/A", rating: "1200", order: 15 },
    { name: "Maxim and Biology", link: "https://codeforces.com/problemset/problem/1151/A", rating: "1200", order: 16 },
    { name: "Vanya and Cards", link: "https://codeforces.com/problemset/problem/401/A", rating: "1200", order: 17 },
    { name: "Dima and Guards", link: "https://codeforces.com/problemset/problem/272/A", rating: "1200", order: 18 },
    { name: "Reconnaissance", link: "https://codeforces.com/problemset/problem/34/A", rating: "1200", order: 19 },
    { name: "Yaroslav and Sequence", link: "https://codeforces.com/problemset/problem/296/B", rating: "1200", order: 20 },
    { name: "Dima and Trap Graph", link: "https://codeforces.com/problemset/problem/366/C", rating: "1200", order: 21 },
    { name: "Jeff and Periods", link: "https://codeforces.com/problemset/problem/352/A", rating: "1200", order: 22 },
    { name: "Vasya and Wrestling", link: "https://codeforces.com/problemset/problem/493/A", rating: "1200", order: 23 },
    { name: "Dima and Hacks", link: "https://codeforces.com/problemset/problem/272/D", rating: "1200", order: 24 },
    { name: "Polo the Penguin and Strings", link: "https://codeforces.com/problemset/problem/289/C", rating: "1200", order: 25 },
    { name: "Xenia and Divisors", link: "https://codeforces.com/problemset/problem/342/A", rating: "1200", order: 26 },
    { name: "Dima and Salad", link: "https://codeforces.com/problemset/problem/366/A", rating: "1200", order: 27 },
    { name: "Inna and Alarm Clock", link: "https://codeforces.com/problemset/problem/374/B", rating: "1200", order: 28 },
    { name: "Vasya and Digital Root", link: "https://codeforces.com/problemset/problem/460/B", rating: "1200", order: 29 },
    { name: "Yaroslav and Divisors", link: "https://codeforces.com/problemset/problem/296/C", rating: "1200", order: 30 }
];

export const USACO_PROBLEMS = [
    // Bronze
    { name: "Promotion Counting", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=591", rating: "Bronze", order: 1 },
    { name: "Word Processor", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=987", rating: "Bronze", order: 2 },
    { name: "Cow Signal", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=665", rating: "Bronze", order: 3 },
    { name: "Speeding Ticket", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=568", rating: "Bronze", order: 4 },
    { name: "The Lost Cow", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=735", rating: "Bronze", order: 5 },
    { name: "The Bovine Shuffle", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=760", rating: "Bronze", order: 6 },
    { name: "Milk Pails", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=615", rating: "Bronze", order: 7 },
    { name: "Diamond Collector", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=639", rating: "Bronze", order: 8 },
    { name: "Cow Gymnastics", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=963", rating: "Bronze", order: 9 },
    { name: "Shell Game", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=891", rating: "Bronze", order: 10 },
    { name: "Mixing Milk", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=855", rating: "Bronze", order: 11 },
    { name: "Bucket Brigade", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=939", rating: "Bronze", order: 12 },
    { name: "Back and Forth", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=857", rating: "Bronze", order: 13 },
    { name: "Team Tic Tac Toe", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=831", rating: "Bronze", order: 14 },
    { name: "Why Did the Cow Cross the Road", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=712", rating: "Bronze", order: 15 },
    { name: "Teleportation", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=807", rating: "Bronze", order: 16 },
    { name: "Block Game", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=664", rating: "Bronze", order: 17 },
    { name: "Angry Cows", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=592", rating: "Bronze", order: 18 },
    { name: "Load Balancing", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=617", rating: "Bronze", order: 19 },
    { name: "Circular Barn", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=616", rating: "Bronze", order: 20 },
    { name: "Cow Evolution", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=941", rating: "Bronze", order: 21 },
    { name: "Milk Measurement", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=761", rating: "Bronze", order: 22 },
    { name: "Modern Art", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=737", rating: "Bronze", order: 23 },
    { name: "Lifeguards", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=784", rating: "Bronze", order: 24 },
    { name: "Taming the Herd", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=787", rating: "Bronze", order: 25 },
    { name: "Measuring Traffic", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=917", rating: "Bronze", order: 26 },
    { name: "Sleepy Cow Herding", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=915", rating: "Bronze", order: 27 },
    { name: "Cow Tipping", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=689", rating: "Bronze", order: 28 },
    { name: "Mowing the Field", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=593", rating: "Bronze", order: 29 },
    { name: "Field Reduction", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=642", rating: "Bronze", order: 30 },

    // Silver
    { name: "High Card Wins", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=571", rating: "Silver", order: 1 },
    { name: "Breed Counting", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=572", rating: "Silver", order: 2 },
    { name: "Subsequences Summing to Sevens", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=595", rating: "Silver", order: 3 },
    { name: "Hoof, Paper, Scissors", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=691", rating: "Silver", order: 4 },
    { name: "Paired Up", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=738", rating: "Silver", order: 5 },
    { name: "Diamond Collector", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=643", rating: "Silver", order: 6 },
    { name: "Counting Haybales", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=666", rating: "Silver", order: 7 },
    { name: "Convention", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=858", rating: "Silver", order: 8 },
    { name: "Angry Cows", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=594", rating: "Silver", order: 9 },
    { name: "Social Distancing", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=1038", rating: "Silver", order: 10 },
    { name: "Wormhole Sort", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=992", rating: "Silver", order: 11 },
    { name: "Moocast", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=668", rating: "Silver", order: 12 },
    { name: "Closing the Farm", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=646", rating: "Silver", order: 13 },
    { name: "Switching on the Lights", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=570", rating: "Silver", order: 14 },
    { name: "Building Roads", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=690", rating: "Silver", order: 15 },
    { name: "Milk Visits", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=968", rating: "Silver", order: 16 },
    { name: "Cow Dance Show", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=690", rating: "Silver", order: 17 },
    { name: "Berry Picking", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=990", rating: "Silver", order: 18 },
    { name: "Rental Service", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=787", rating: "Silver", order: 19 },
    { name: "Rest Stops", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=810", rating: "Silver", order: 20 },
    { name: "Lemonade Line", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=835", rating: "Silver", order: 21 },
    { name: "Out of Sorts", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=834", rating: "Silver", order: 22 },
    { name: "Milk Measurement", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=763", rating: "Silver", order: 23 },
    { name: "Lifeguards", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=786", rating: "Silver", order: 24 },
    { name: "The Bovine Shuffle", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=764", rating: "Silver", order: 25 },
    { name: "Snow Boots", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=813", rating: "Silver", order: 26 },
    { name: "Mooyo Mooyo", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=860", rating: "Silver", order: 27 },
    { name: "Multiplayer Moo", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=836", rating: "Silver", order: 28 },
    { name: "Icy Perimeter", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=895", rating: "Silver", order: 29 },
    { name: "Visits", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=967", rating: "Silver", order: 30 },

    // Gold
    { name: "Cow Checklist", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=670", rating: "Gold", order: 1 },
    { name: "Fruit Feast", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=574", rating: "Gold", order: 2 },
    { name: "Circular Barn Revisited", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=622", rating: "Gold", order: 3 },
    { name: "248", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=647", rating: "Gold", order: 4 },
    { name: "Taming the Herd", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=815", rating: "Gold", order: 5 },
    { name: "Talent Show", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=839", rating: "Gold", order: 6 },
    { name: "Teamwork", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=863", rating: "Gold", order: 7 },
    { name: "Snakes", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=945", rating: "Gold", order: 8 },
    { name: "Moortal Cowmbat", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=971", rating: "Gold", order: 9 },
    { name: "Time is Mooney", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=993", rating: "Gold", order: 10 },
    { name: "Milk Pumping", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=969", rating: "Gold", order: 11 },
    { name: "Shortcut", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=899", rating: "Gold", order: 12 },
    { name: "Fine Dining", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=861", rating: "Gold", order: 13 },
    { name: "Cow Navigation", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=695", rating: "Gold", order: 14 },
    { name: "Bessie's Dream", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=575", rating: "Gold", order: 15 },
    { name: "Moocast", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=669", rating: "Gold", order: 16 },
    { name: "Fenced In", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=623", rating: "Gold", order: 17 },
    { name: "Closing the Farm", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=646", rating: "Gold", order: 18 },
    { name: "Milking Order", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=838", rating: "Gold", order: 19 },
    { name: "Timeline", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=1017", rating: "Gold", order: 20 },
    { name: "Moortal Kombat", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=971", rating: "Gold", order: 21 },
    { name: "Cow Land", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=921", rating: "Gold", order: 22 },
    { name: "Milk Visits", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=970", rating: "Gold", order: 23 },
    { name: "Exercise", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=901", rating: "Gold", order: 24 },
    { name: "Cow Poetry", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=897", rating: "Gold", order: 25 },
    { name: "I Would Walk 500 Miles", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=946", rating: "Gold", order: 26 },
    { name: "Balanced Photo", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=693", rating: "Gold", order: 27 },
    { name: "Modern Art 2", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=743", rating: "Gold", order: 28 },
    { name: "Haybale Feast", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=767", rating: "Gold", order: 29 },
    { name: "Sleepy Cow Sorting", link: "http://www.usaco.org/index.php?page=viewproblem2&cpid=898", rating: "Gold", order: 30 }
];

export const CSES_PROBLEMS = [
    // Introductory Problems
    { name: "Weird Algorithm", link: "https://cses.fi/problemset/task/1068", rating: "Intro", order: 1 },
    { name: "Missing Number", link: "https://cses.fi/problemset/task/1083", rating: "Intro", order: 2 },
    { name: "Repetitions", link: "https://cses.fi/problemset/task/1069", rating: "Intro", order: 3 },
    { name: "Increasing Array", link: "https://cses.fi/problemset/task/1094", rating: "Intro", order: 4 },
    { name: "Permutations", link: "https://cses.fi/problemset/task/1070", rating: "Intro", order: 5 },
    { name: "Number Spiral", link: "https://cses.fi/problemset/task/1071", rating: "Intro", order: 6 },
    { name: "Two Knights", link: "https://cses.fi/problemset/task/1072", rating: "Intro", order: 7 },
    { name: "Two Sets", link: "https://cses.fi/problemset/task/1092", rating: "Intro", order: 8 },
    { name: "Bit Strings", link: "https://cses.fi/problemset/task/1617", rating: "Intro", order: 9 },
    { name: "Trailing Zeros", link: "https://cses.fi/problemset/task/1618", rating: "Intro", order: 10 },
    { name: "Coin Piles", link: "https://cses.fi/problemset/task/1754", rating: "Intro", order: 11 },
    { name: "Palindrome Reorder", link: "https://cses.fi/problemset/task/1755", rating: "Intro", order: 12 },
    { name: "Gray Code", link: "https://cses.fi/problemset/task/2205", rating: "Intro", order: 13 },
    { name: "Tower of Hanoi", link: "https://cses.fi/problemset/task/2165", rating: "Intro", order: 14 },
    { name: "Creating Strings", link: "https://cses.fi/problemset/task/1622", rating: "Intro", order: 15 },
    { name: "Apple Division", link: "https://cses.fi/problemset/task/1623", rating: "Intro", order: 16 },
    { name: "Chessboard and Queens", link: "https://cses.fi/problemset/task/1624", rating: "Intro", order: 17 },
    { name: "Digit Queries", link: "https://cses.fi/problemset/task/2431", rating: "Intro", order: 18 },
    { name: "Grid Paths", link: "https://cses.fi/problemset/task/1625", rating: "Intro", order: 19 },

    // Sorting and Searching
    { name: "Distinct Numbers", link: "https://cses.fi/problemset/task/1621", rating: "Sorting", order: 1 },
    { name: "Apartments", link: "https://cses.fi/problemset/task/1084", rating: "Sorting", order: 2 },
    { name: "Ferris Wheel", link: "https://cses.fi/problemset/task/1090", rating: "Sorting", order: 3 },
    { name: "Concert Tickets", link: "https://cses.fi/problemset/task/1091", rating: "Sorting", order: 4 },
    { name: "Restaurant Customers", link: "https://cses.fi/problemset/task/1619", rating: "Sorting", order: 5 },
    { name: "Movie Festival", link: "https://cses.fi/problemset/task/1629", rating: "Sorting", order: 6 },
    { name: "Sum of Two Values", link: "https://cses.fi/problemset/task/1640", rating: "Sorting", order: 7 },
    { name: "Maximum Subarray Sum", link: "https://cses.fi/problemset/task/1643", rating: "Sorting", order: 8 },
    { name: "Stick Lengths", link: "https://cses.fi/problemset/task/1074", rating: "Sorting", order: 9 },
    { name: "Playlist", link: "https://cses.fi/problemset/task/1141", rating: "Sorting", order: 10 },
    { name: "Towers", link: "https://cses.fi/problemset/task/1073", rating: "Sorting", order: 11 },
    { name: "Traffic Lights", link: "https://cses.fi/problemset/task/1163", rating: "Sorting", order: 12 },
    { name: "Room Allocation", link: "https://cses.fi/problemset/task/1164", rating: "Sorting", order: 13 },
    { name: "Factory Machines", link: "https://cses.fi/problemset/task/1620", rating: "Sorting", order: 14 },
    { name: "Tasks and Deadlines", link: "https://cses.fi/problemset/task/1630", rating: "Sorting", order: 15 },
    { name: "Reading Books", link: "https://cses.fi/problemset/task/1631", rating: "Sorting", order: 16 },
    { name: "Sum of Three Values", link: "https://cses.fi/problemset/task/1641", rating: "Sorting", order: 17 },
    { name: "Sum of Four Values", link: "https://cses.fi/problemset/task/1642", rating: "Sorting", order: 18 },
    { name: "Nearest Smaller Values", link: "https://cses.fi/problemset/task/1645", rating: "Sorting", order: 19 },
    { name: "Subarray Sums I", link: "https://cses.fi/problemset/task/1660", rating: "Sorting", order: 20 },
    { name: "Subarray Sums II", link: "https://cses.fi/problemset/task/1661", rating: "Sorting", order: 21 },
    { name: "Subarray Divisibility", link: "https://cses.fi/problemset/task/1662", rating: "Sorting", order: 22 },
    { name: "Subarray Distinct Values", link: "https://cses.fi/problemset/task/2428", rating: "Sorting", order: 23 },
    { name: "Array Division", link: "https://cses.fi/problemset/task/1085", rating: "Sorting", order: 24 },
    { name: "Sliding Median", link: "https://cses.fi/problemset/task/1076", rating: "Sorting", order: 25 },
    { name: "Sliding Cost", link: "https://cses.fi/problemset/task/1077", rating: "Sorting", order: 26 },
    { name: "Movie Festival II", link: "https://cses.fi/problemset/task/1632", rating: "Sorting", order: 27 },
    { name: "Maximum Subarray Sum II", link: "https://cses.fi/problemset/task/1644", rating: "Sorting", order: 28 },

    // Dynamic Programming
    { name: "Dice Combinations", link: "https://cses.fi/problemset/task/1633", rating: "DP", order: 1 },
    { name: "Minimizing Coins", link: "https://cses.fi/problemset/task/1634", rating: "DP", order: 2 },
    { name: "Coin Combinations I", link: "https://cses.fi/problemset/task/1635", rating: "DP", order: 3 },
    { name: "Coin Combinations II", link: "https://cses.fi/problemset/task/1636", rating: "DP", order: 4 },
    { name: "Removing Digits", link: "https://cses.fi/problemset/task/1637", rating: "DP", order: 5 },
    { name: "Grid Paths", link: "https://cses.fi/problemset/task/1638", rating: "DP", order: 6 },
    { name: "Book Shop", link: "https://cses.fi/problemset/task/1158", rating: "DP", order: 7 },
    { name: "Array Description", link: "https://cses.fi/problemset/task/1746", rating: "DP", order: 8 },
    { name: "Counting Towers", link: "https://cses.fi/problemset/task/2413", rating: "DP", order: 9 },
    { name: "Edit Distance", link: "https://cses.fi/problemset/task/1639", rating: "DP", order: 10 },
    { name: "Rectangle Cutting", link: "https://cses.fi/problemset/task/1744", rating: "DP", order: 11 },
    { name: "Money Sums", link: "https://cses.fi/problemset/task/1745", rating: "DP", order: 12 },
    { name: "Removal Game", link: "https://cses.fi/problemset/task/1097", rating: "DP", order: 13 },
    { name: "Two Sets II", link: "https://cses.fi/problemset/task/1093", rating: "DP", order: 14 },
    { name: "Increasing Subsequence", link: "https://cses.fi/problemset/task/1145", rating: "DP", order: 15 },
    { name: "Projects", link: "https://cses.fi/problemset/task/1140", rating: "DP", order: 16 },
    { name: "Elevator Rides", link: "https://cses.fi/problemset/task/1653", rating: "DP", order: 17 },
    { name: "Counting Tilings", link: "https://cses.fi/problemset/task/2181", rating: "DP", order: 18 },
    { name: "Counting Numbers", link: "https://cses.fi/problemset/task/2220", rating: "DP", order: 19 },

    // Graph Algorithms
    { name: "Counting Rooms", link: "https://cses.fi/problemset/task/1192", rating: "Graph", order: 1 },
    { name: "Labyrinth", link: "https://cses.fi/problemset/task/1193", rating: "Graph", order: 2 },
    { name: "Building Roads", link: "https://cses.fi/problemset/task/1666", rating: "Graph", order: 3 },
    { name: "Message Route", link: "https://cses.fi/problemset/task/1667", rating: "Graph", order: 4 },
    { name: "Building Teams", link: "https://cses.fi/problemset/task/1668", rating: "Graph", order: 5 },
    { name: "Round Trip", link: "https://cses.fi/problemset/task/1669", rating: "Graph", order: 6 },
    { name: "Monsters", link: "https://cses.fi/problemset/task/1194", rating: "Graph", order: 7 },
    { name: "Shortest Routes I", link: "https://cses.fi/problemset/task/1671", rating: "Graph", order: 8 },
    { name: "Shortest Routes II", link: "https://cses.fi/problemset/task/1672", rating: "Graph", order: 9 },
    { name: "High Score", link: "https://cses.fi/problemset/task/1673", rating: "Graph", order: 10 },
    { name: "Flight Discount", link: "https://cses.fi/problemset/task/1195", rating: "Graph", order: 11 },
    { name: "Cycle Finding", link: "https://cses.fi/problemset/task/1197", rating: "Graph", order: 12 },
    { name: "Flight Routes", link: "https://cses.fi/problemset/task/1196", rating: "Graph", order: 13 },
    { name: "Round Trip II", link: "https://cses.fi/problemset/task/1678", rating: "Graph", order: 14 },
    { name: "Course Schedule", link: "https://cses.fi/problemset/task/1679", rating: "Graph", order: 15 },
    { name: "Longest Flight Route", link: "https://cses.fi/problemset/task/1680", rating: "Graph", order: 16 },
    { name: "Game Routes", link: "https://cses.fi/problemset/task/1681", rating: "Graph", order: 17 },
    { name: "Investigation", link: "https://cses.fi/problemset/task/1202", rating: "Graph", order: 18 },
    { name: "Planets Queries I", link: "https://cses.fi/problemset/task/1750", rating: "Graph", order: 19 },
    { name: "Planets Queries II", link: "https://cses.fi/problemset/task/1160", rating: "Graph", order: 20 },
    { name: "Planets Cycles", link: "https://cses.fi/problemset/task/1751", rating: "Graph", order: 21 },
    { name: "Road Reparation", link: "https://cses.fi/problemset/task/1675", rating: "Graph", order: 22 },
    { name: "Road Construction", link: "https://cses.fi/problemset/task/1676", rating: "Graph", order: 23 },
    { name: "Flight Routes Check", link: "https://cses.fi/problemset/task/1682", rating: "Graph", order: 24 },
    { name: "Planets and Kingdoms", link: "https://cses.fi/problemset/task/1683", rating: "Graph", order: 25 },
    { name: "Giant Pizza", link: "https://cses.fi/problemset/task/1684", rating: "Graph", order: 26 },
    { name: "Coin Collector", link: "https://cses.fi/problemset/task/1686", rating: "Graph", order: 27 },
    { name: "Mail Delivery", link: "https://cses.fi/problemset/task/1691", rating: "Graph", order: 28 },
    { name: "De Bruijn Sequence", link: "https://cses.fi/problemset/task/1692", rating: "Graph", order: 29 },
    { name: "Teleporters Path", link: "https://cses.fi/problemset/task/1693", rating: "Graph", order: 30 }
];
